name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:    

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          config_timezone: Asia/Ho_Chi_Minh

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year 
